// Generates src/lib/icons.js from lucide-static: only the icons we use, as
// inner SVG markup, so the client needs no icon font or CDN.
//   npm run icons
import { readFileSync, writeFileSync } from 'node:fs';

const ICONS = [
  'message-square', 'layout-grid', 'history', 'cloud', 'folder', 'folder-open', 'folder-plus', 'file', 'file-text', 'file-image', 'file-video',
  'file-audio', 'file-archive', 'file-code', 'upload', 'download', 'pencil', 'move', 'share-2', 'link',
  'trash-2', 'ellipsis', 'chevron-right', 'log-out', 'settings', 'users', 'user', 'lock', 'key-round',
  'shield-check', 'fingerprint', 'copy', 'check', 'x', 'sun', 'moon', 'monitor', 'hard-drive', 'inbox', 'globe',
  'refresh-cw', 'circle-alert', 'loader-circle', 'arrow-left', 'house', 'plus', 'file-up', 'eye', 'eye-off',
  'user-round-plus', 'door-open', 'chevron-left', 'zoom-in', 'zoom-out', 'code', 'book-open', 'wrap-text',
  'undo-2', 'redo-2', 'heading-1', 'heading-2', 'heading-3', 'bold', 'italic', 'strikethrough', 'list', 'list-ordered',
  'list-todo', 'text-quote', 'square-code', 'minus', 'file-plus', 'save', 'search', 'arrow-up', 'arrow-down', 'keyboard', 'folder-up', 'chevron-down', 'laptop', 'smartphone', 'file-cog', 'lock-open',
  'list-checks', 'table', 'between-horizontal-end', 'between-vertical-end', 'grid-2x2-x', 'columns-2',
  'music', 'play', 'pause', 'skip-forward', 'skip-back', 'shuffle', 'repeat', 'repeat-1', 'volume-2', 'volume-1', 'volume-x',
  'list-music', 'disc-3', 'audio-lines', 'list-start', 'list-end',
  'list-plus', 'image', 'clapperboard', 'tv', 'film', 'star', 'star-off', 'clock', 'captions', 'notebook-pen', 'pin', 'pin-off',
  'heart-pulse', 'scale', 'ruler', 'activity',
];

const out = {};
for (const name of ICONS) {
  const svg = readFileSync(`node_modules/lucide-static/icons/${name}.svg`, 'utf8');
  const inner = svg.slice(svg.indexOf('>', svg.indexOf('<svg')) + 1, svg.lastIndexOf('</svg>'));
  out[name] = inner.replace(/\s*\n\s*/g, '').trim();
}
const version = JSON.parse(readFileSync('node_modules/lucide-static/package.json', 'utf8')).version;
writeFileSync(
  'src/lib/icons.js',
  `// Generated by scripts/gen-icons.mjs from lucide-static v${version} (ISC license, https://lucide.dev).\n` +
    `// Do not edit by hand; add names to the list in the script and run \`npm run icons\`.\n\n` +
    `export const ICONS = ${JSON.stringify(out, null, 2)};\n`,
);
console.log(`wrote ${ICONS.length} icons`);
